# Generated by Django 4.2 on 2026-04-10 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0002_learninggoal_usercareergoal_learningprogress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='close_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
